=== crunchdao/competitions/schema/quickstarter.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "A quickstarter schema",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "link": {
                        "type": "string"
                    },
                    "additionalProperties": false
                },
                "required": [
                    "name"
                ]
            }
        },
        "language": {
            "type": "string",
            "enum": [
                "PYTHON",
                "R"
            ]
        },
        "usage": {
            "type": "string",
            "enum": [
                "SUBMISSION",
                "EXPLORATION"
            ]
        },
        "deprecated": {
            "type": "boolean",
            "default": false
        },
        "notebook": {
            "type": "boolean"
        },
        "entrypoint": {
            "type": "string"
        },
        "kaggleUrl": {
            "type": "string",
            "format": "uri"
        },
        "files": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "title",
        "authors",
        "language",
        "usage",
        "notebook",
        "entrypoint"
    ],
    "oneOf": [
        {
            "$comment": "if `notebook`, do not require `files`",
            "properties": {
                "notebook": {
                    "const": true
                }
            },
            "not": {
                "required": [
                    "files"
                ]
            }
        },
        {
            "$comment": "if not `notebook`, do require `files`",
            "properties": {
                "notebook": {
                    "const": false
                }
            },
            "required": [
                "files"
            ]
        }
    ]
}

=== crunchdao/competitions/competitions/adialab/quickstarters/basic-submission/quickstarter.json
{
    "title": "Basic Submission",
    "authors": [
        {
            "name": "Jean Herelle",
            "link": "https://github.com/jeheran"
        },
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "basic-submission.ipynb"
}

=== crunchdao/competitions/competitions/adialab/quickstarters/mlxtend-sharpbased-loss-reg/quickstarter.json
{
    "title": "mlxtend Sharpbased Loss Reg",
    "authors": [
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "mlxtend-sharpbased-loss-reg.ipynb"
}

=== crunchdao/competitions/competitions/datacrunch-legacy/quickstarters/walk-forward-cross-validation/quickstarter.json
{
    "title": "Walk Forward Cross Validation",
    "authors": [
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        },
        {
            "name": "Xavier de Vautibault",
            "link": "https://github.com/xaviergilbert"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "deprecated": true,
    "entrypoint": "walk-forward-cross-validation.ipynb"
}

=== crunchdao/competitions/competitions/broad-obesity-1/quickstarters/regression-baseline/quickstarter.json
{
    "title": "Regression Baseline",
    "authors": [
        {
            "name": "Alexis GASSMANN",
            "link": "https://github.com/Tarandro"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "regression-baseline.ipynb",
    "kaggleUrl": "https://www.kaggle.com/code/crunchdao/broad-obesity-1-regression-baseline"
}

=== crunchdao/competitions/competitions/adialab/quickstarters/boruta-feature-selection/quickstarter.json
{
    "title": "Boruta Feature Selection",
    "authors": [
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "boruta-feature-selection.ipynb"
}

=== crunchdao/competitions/competitions/adialab/quickstarters/advanced-modelling-analysis/quickstarter.json
{
    "title": "Advanced Modelling Analysis",
    "authors": [
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        }
    ],
    "language": "PYTHON",
    "usage": "EXPLORATION",
    "notebook": true,
    "entrypoint": "advanced-modelling-analysis.ipynb"
}

=== crunchdao/competitions/competitions/datacrunch-legacy/quickstarters/quickstarter-notebook-master-2-0/quickstarter.json
{
    "title": "QuickStarter Notebook Master 2.0",
    "authors": [
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "quickstarter-notebook-master-2-0.ipynb"
}

=== crunchdao/competitions/competitions/adialab/quickstarters/sklego-group-timeseries-split/quickstarter.json
{
    "title": "sklego Group Timeseries Split",
    "authors": [
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "sklego-group-timeseries-split.ipynb"
}
