=== crunchdao/competitions/schema/quickstarter.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "A quickstarter schema",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "link": {
                        "type": "string"
                    },
                    "additionalProperties": false
                },
                "required": [
                    "name"
                ]
            }
        },
        "language": {
            "type": "string",
            "enum": [
                "PYTHON",
                "R"
            ]
        },
        "usage": {
            "type": "string",
            "enum": [
                "SUBMISSION",
                "EXPLORATION"
            ]
        },
        "deprecated": {
            "type": "boolean",
            "default": false
        },
        "notebook": {
            "type": "boolean"
        },
        "entrypoint": {
            "type": "string"
        },
        "kaggleUrl": {
            "type": "string",
            "format": "uri"
        },
        "files": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "title",
        "authors",
        "language",
        "usage",
        "notebook",
        "entrypoint"
    ],
    "oneOf": [
        {
            "$comment": "if `notebook`, do not require `files`",
            "properties": {
                "notebook": {
                    "const": true
                }
            },
            "not": {
                "required": [
                    "files"
                ]
            }
        },
        {
            "$comment": "if not `notebook`, do require `files`",
            "properties": {
                "notebook": {
                    "const": false
                }
            },
            "required": [
                "files"
            ]
        }
    ]
}

=== crunchdao/competitions/competitions/datacrunch-legacy/quickstarters/r-example/quickstarter.json
{
    "title": "R Example",
    "authors": [
        {
            "name": "RWarnung",
            "link": "https://github.com/rwarnung"
        },
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        },
        {
            "name": "Xavier de Vautibault",
            "link": "https://github.com/xaviergilbert"
        }
    ],
    "language": "R",
    "usage": "SUBMISSION",
    "notebook": true,
    "deprecated": true,
    "entrypoint": "r-example.ipynb"
}

=== crunchdao/competitions/competitions/adialab/quickstarters/advanced-exploratory-data-analysis/quickstarter.json
{
    "title": "Advanced Exploratory Data Analysis",
    "authors": [
        {
            "name": "Jean Herelle",
            "link": "https://github.com/jeheran"
        },
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        }
    ],
    "language": "PYTHON",
    "usage": "EXPLORATION",
    "notebook": true,
    "entrypoint": "advanced-exploratory-data-analysis.ipynb"
}

=== crunchdao/competitions/competitions/btcdvol/quickstarters/getting-started/quickstarter.json
{
    "title": "Getting Started",
    "authors": [
        {
            "name": "Jeremy Berros",
            "link": "https://github.com/jberros"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "https://github.com/jberros/crunch-btcdvol/blob/main/notebooks/GETTING_STARTED.ipynb"
}

=== crunchdao/competitions/competitions/datacrunch-legacy/quickstarters/feature_engineering/quickstarter.json
{
    "title": "Feature Engineering",
    "authors": [
        {
            "name": "Shreenidhi Hipparagi",
            "link": "https://github.com/Shreenidhi1999"
        },
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        },
        {
            "name": "Jean Herelle",
            "link": "https://github.com/jeheran"
        }
    ],
    "language": "PYTHON",
    "usage": "EXPLORATION",
    "notebook": true,
    "deprecated": true,
    "entrypoint": "feature_engineering.ipynb"
}

=== crunchdao/competitions/competitions/falcon/quickstarters/ewma-variance/quickstarter.json
{
    "title": "EWMA Variance",
    "authors": [
        {
            "name": "Alexis GASSMANN",
            "link": "https://github.com/Tarandro"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "https://github.com/microprediction/birdgame/blob/main/birdgame/examples/quickstarters/ewma_var.ipynb"
}

=== crunchdao/competitions/competitions/datacrunch-legacy/quickstarters/feature-selection/quickstarter.json
{
    "title": "Feature Selection",
    "authors": [
        {
            "name": "Shreenidhi Hipparagi",
            "link": "https://github.com/Shreenidhi1999"
        },
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        },
        {
            "name": "Jean Herelle",
            "link": "https://github.com/jeheran"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "deprecated": true,
    "entrypoint": "feature-selection.ipynb"
}

=== crunchdao/competitions/competitions/structural-break-open-benchmark/quickstarters/baseline/quickstarter.json
{
    "title": "Baseline",
    "description": "Uses a t-test to compare the distributions before and after the boundary point.",
    "authors": [
        {
            "name": "ADIA Lab"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "baseline.ipynb",
    "kaggleUrl": "https://www.kaggle.com/code/crunchdao/structural-break-open-benchmark-baseline"
}

=== crunchdao/competitions/competitions/broad-obesity-2/quickstarters/perturbed-mean-baseline/quickstarter.json
{
    "title": "Perturbed Mean Baseline",
    "authors": [
        {
            "name": "The Eric and Wendy Schmidt Center Team at the Broad Institute",
            "link": "https://www.broadinstitute.org/"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "perturbed-mean-baseline.ipynb"
}
