=== crunchdao/competitions/schema/quickstarter.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "A quickstarter schema",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "link": {
                        "type": "string"
                    },
                    "additionalProperties": false
                },
                "required": [
                    "name"
                ]
            }
        },
        "language": {
            "type": "string",
            "enum": [
                "PYTHON",
                "R"
            ]
        },
        "usage": {
            "type": "string",
            "enum": [
                "SUBMISSION",
                "EXPLORATION"
            ]
        },
        "deprecated": {
            "type": "boolean",
            "default": false
        },
        "notebook": {
            "type": "boolean"
        },
        "entrypoint": {
            "type": "string"
        },
        "kaggleUrl": {
            "type": "string",
            "format": "uri"
        },
        "files": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "title",
        "authors",
        "language",
        "usage",
        "notebook",
        "entrypoint"
    ],
    "oneOf": [
        {
            "$comment": "if `notebook`, do not require `files`",
            "properties": {
                "notebook": {
                    "const": true
                }
            },
            "not": {
                "required": [
                    "files"
                ]
            }
        },
        {
            "$comment": "if not `notebook`, do require `files`",
            "properties": {
                "notebook": {
                    "const": false
                }
            },
            "required": [
                "files"
            ]
        }
    ]
}

=== crunchdao/competitions/competitions/venture-capital-portfolio-prediction/quickstarters/quickstarter-random-forest/quickstarter.json
{
    "title": "QuickStarter Random Forest",
    "authors": [
        {
            "name": "Zoe Mavroeidi",
            "link": "https://github.com/zoe-mav"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "quickstarter-random-forest.ipynb"
}

=== crunchdao/competitions/competitions/datacrunch-2/quickstarters/financial-eda-deep-dive/quickstarter.json
{
    "title": "Financial EDA Deep Dive",
    "authors": [
        {
            "name": "Xavier Gilbert",
            "link": "https://github.com/xaviergilbert"
        }
    ],
    "language": "PYTHON",
    "usage": "EXPLORATION",
    "notebook": true,
    "entrypoint": "financial-eda-deep-dive.ipynb"
}

=== crunchdao/competitions/competitions/structural-break-real-time/quickstarters/baseline/quickstarter.json
{
    "title": "Baseline",
    "description": "Uses a t-test to compare the distributions before and after the boundary point.",
    "authors": [
        {
            "name": "ADIA Lab"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "baseline.ipynb"
}

=== crunchdao/competitions/competitions/broad-obesity-1/quickstarters/perturbed-mean-baseline/quickstarter.json
{
    "title": "Perturbed Mean Baseline",
    "authors": [
        {
            "name": "The Eric and Wendy Schmidt Center Team at the Broad Institute",
            "link": "https://www.broadinstitute.org/"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "perturbed-mean-baseline.ipynb",
    "kaggleUrl": "https://www.kaggle.com/code/crunchdao/broad-obesity-1-perturbed-mean-baseline"
}

=== crunchdao/competitions/competitions/adialab/quickstarters/group-timeseries-split/quickstarter.json
{
    "title": "Group Timeseries Split",
    "authors": [
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        },
        {
            "name": "Xavier de Vautibault",
            "link": "https://github.com/xaviergilbert"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "group-timeseries-split.ipynb"
}

=== crunchdao/competitions/competitions/synth/quickstarters/example-tracker/quickstarter.json
{
    "title": "Example Tracker",
    "authors": [
        {
            "name": "CrunchDAO",
            "link": "https://github.com/crunchdao"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "https://github.com/crunchdao/crunch-synth/blob/master/crunch_synth/examples/exampletracker.ipynb"
}

=== crunchdao/competitions/competitions/datacrunch-legacy/quickstarters/exploratory-data-analysis/quickstarter.json
{
    "title": "Exploratory Data Analysis",
    "authors": [
        {
            "name": "Matteo Manzi",
            "link": "https://github.com/matteoettam09"
        }
    ],
    "language": "PYTHON",
    "usage": "EXPLORATION",
    "notebook": true,
    "entrypoint": "exploratory-data-analysis.ipynb"
}

=== crunchdao/competitions/competitions/numinous/quickstarters/example-tracker/quickstarter.json
{
    "title": "Example Tracker",
    "authors": [
        {
            "name": "CrunchDAO",
            "link": "https://github.com/crunchdao"
        }
    ],
    "language": "PYTHON",
    "usage": "SUBMISSION",
    "notebook": true,
    "entrypoint": "https://github.com/crunchdao/numinous/blob/main/challenge/numinous/examples/quickstart.ipynb"
}
